version: '3'
services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
  laptop-service:
    build: ./laptop
    ports:
      - "5000:5000"
    environment:
      - DB_PORT_27017_TCP_ADDR=mongo
    depends_on:
      - mongo
  website:
    build: ./website
    ports:
      - "80:80"
    depends_on:
      - laptop-service
